import numpy as np;
array_1d=np.array([1,2,3,4,5])
print("\n1DArray before insertion:")
print(array_1d)
array_1d=np.insert(array_1d,2,9)
print("\n1D Array after insertion")
print(array_1d)
array_2d=np.array([[1,2,3],[4,5,6]])
print("\nOriginal 2D array")
print(array_2d)
array_2d=np.insert(array_2d,2,[7,8,9],axis=0)
print("\n2D Array after Insertion")
print(array_2d)