import numpy as np;
arr_id=np.array([1,2,3,4,5])
diagonal_matrix=np.diag(arr_id)
print("1D array:")
print(arr_id)
print("Diagonal Matrix")
print(diagonal_matrix)
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
diag_matrix=np.diag(array_2d)
print("2D array")
print(array_2d)
print("Diagonal elements of 2d array")
print(diag_matrix )
array_2d_nonsquare=np.array([[1,2,3],[4,5,6]])
diagonal_matrix_square=np.diag(array_2d_nonsquare)
print("Array")
print(array_2d_nonsquare)
print("Diagonal elements non square")
print(diagonal_matrix_square)